spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.159.135:3306/springcloud_Sell?charactEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.159.135
    port: 5672
    password: guest
    username: guest  
